packages:
  - 'configs/*'
  - 'core/*'
  - 'plugins/*'
  - 'incubator/ember-controls-modifier/package'
  - 'incubator/ember-controls-modifier/test-app'
  - 'incubator/*'
  #- 'explorer'
  - 'ember/*/package'
  - 'ember/*/test-app'
  - 'ember/asset-loader'
  - 'themes/*'
