packages:
  - 'configs/*'
  - 'foundation/*'
  - 'plugins/*'
  - 'incubator/ember-aria-navigator/package'
  - 'incubator/ember-aria-navigator/test-app'
  - 'incubator/*'
  - 'explorer'
  - 'ember/*'
  - 'themes/*'
