name: 'CI'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-js:
    name: lint:js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run -r --parallel --aggregate-output lint:js

  lint-css:
    name: lint:css
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run -r --parallel --aggregate-output lint:css

  lint-hbs:
    name: lint:hbs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run -r --parallel --aggregate-output lint:hbs

  lint-types:
    name: lint:types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run -r --parallel --aggregate-output lint:types

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Test
        run: pnpm run -r --parallel --aggregate-output test

  test-ember:
    name: Test Ember
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - CSR
          - SSR
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Try Scenario
        run: pnpm exec ember try:one ${{ matrix.try-scenario }} --skip-cleanup
        working-directory: ember/test-app
