name: 'CI'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-js:
    name: lint:js
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run -r --parallel --aggregate-output lint:js

  lint-css:
    name: lint:css
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup
        env:
          COVERAGE: true
      - run: pnpm run -r --parallel --aggregate-output lint:css

  lint-hbs:
    name: lint:hbs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: pnpm build
      - run: pnpm run -r --parallel --aggregate-output lint:hbs

  lint-types:
    name: lint:types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: pnpm build
      - run: pnpm run -r --parallel --aggregate-output lint:types

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: pnpm build
      - name: Test
        run: pnpm run -r --parallel --aggregate-output test
