name: 'Coverage'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: wyvox/action@v1
      - name: Build package
        run: COVERAGE=true pnpm build
      - name: coverage
        uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          COVERAGE: true
        with:
          coverageCommand: pnpm run -r --parallel --aggregate-output test
          coverageLocations: |
            ${{github.workspace}}/ember/test-app/coverage/lcov.info:lcov
