name: 'Coverage'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        env:
          COVERAGE: true

      # - uses: actions/checkout@v4
      # - name: Install pnpm
      #   uses: pnpm/action-setup@v4
      # - name: Use Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version-file: '.node-version'
      #     cache: 'pnpm'
      # - name: Install dependencies
      #   run: pnpm install
      # - name: Build package
      #   run: COVERAGE=true pnpm build
      - run: pnpm run -r --parallel --aggregate-output test
      - run: ls ./ember/test-app/coverage
      - name: coverage
        uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          COVERAGE: true
        with:
          coverageCommand: pnpm run -r --parallel --aggregate-output test
          coverageLocations: |
            ${{github.workspace}}/ember/test-app/coverage/lcov.info:lcov
