name: Coverage

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup
        uses: ./.github/actions/setup
        env:
          COVERAGE: true
      - uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ${{github.workspace}}/ember/package/coverage/lcov.info
